from flask import Blueprint, render_template, redirect, url_for, flash, request, jsonify
from flask_login import login_required, current_user
from datetime import datetime, timedelta
from ..models import db, Denial, PriorAuth, AuditLog
from ..services.ai_service import generate_appeal_letter

denial_bp = Blueprint('denial', __name__)


@denial_bp.route('/denials')
@login_required
def list_denials():
    denials = (Denial.query
        .join(PriorAuth)
        .filter(PriorAuth.practice_id == current_user.practice_id)
        .order_by(Denial.appeal_deadline.asc())
        .all())
    return render_template('prior_auth/denials.html', denials=denials)


@denial_bp.route('/prior-auths/<int:auth_id>/record-denial', methods=['POST'])
@login_required
def record_denial(auth_id):
    auth = PriorAuth.query.filter_by(
        id=auth_id,
        practice_id=current_user.practice_id
    ).first_or_404()

    denial_date_str  = request.form.get('denial_date')
    appeal_days      = int(request.form.get('appeal_days', 30))

    try:
        denial_date = datetime.strptime(denial_date_str, '%Y-%m-%d').date()
    except (ValueError, TypeError):
        denial_date = datetime.utcnow().date()

    appeal_deadline = denial_date + timedelta(days=appeal_days)

    denial = Denial(
        prior_auth_id   = auth.id,
        denial_date     = denial_date,
        denial_reason   = request.form.get('denial_reason', '').strip(),
        denial_code     = request.form.get('denial_code', '').strip(),
        appeal_deadline = appeal_deadline,
        appeal_status   = 'not_started',
    )
    db.session.add(denial)

    auth.status     = 'denied'
    auth.decision_at= datetime.utcnow()

    log = AuditLog(
        practice_id=current_user.practice_id,
        user_id=current_user.id,
        prior_auth_id=auth.id,
        action='DENIAL_RECORDED',
        resource_type='denial',
        notes=f'Denial reason: {denial.denial_reason}',
        ip_address=request.remote_addr
    )
    db.session.add(log)
    db.session.commit()

    flash('Denial recorded. Generate an appeal letter below.', 'warning')
    return redirect(url_for('prior_auth.view_auth', auth_id=auth_id))


@denial_bp.route('/denials/<int:denial_id>/generate-appeal', methods=['POST'])
@login_required
def generate_appeal(denial_id):
    denial = (Denial.query
        .join(PriorAuth)
        .filter(
            Denial.id == denial_id,
            PriorAuth.practice_id == current_user.practice_id
        ).first_or_404())

    auth    = denial.prior_auth
    patient = auth.patient

    # Call the AI service
    letter = generate_appeal_letter(
        patient_name   = patient.full_name,
        payer_name     = auth.payer_name,
        cpt_code       = auth.cpt_code,
        cpt_description= auth.cpt_description or '',
        icd10_code     = auth.icd10_code,
        denial_reason  = denial.denial_reason or 'Not medically necessary',
        clinical_notes = auth.clinical_notes or '',
        provider_name  = auth.provider_name or current_user.practice.name,
    )

    denial.appeal_letter = letter
    denial.appeal_status = 'in_progress'

    log = AuditLog(
        practice_id=current_user.practice_id,
        user_id=current_user.id,
        prior_auth_id=auth.id,
        action='APPEAL_LETTER_GENERATED',
        resource_type='denial',
        resource_id=denial_id,
        ip_address=request.remote_addr
    )
    db.session.add(log)
    db.session.commit()

    flash('Appeal letter generated by AI. Review and edit before sending.', 'success')
    return redirect(url_for('prior_auth.view_auth', auth_id=auth.id))


@denial_bp.route('/denials/<int:denial_id>/update', methods=['POST'])
@login_required
def update_denial(denial_id):
    denial = (Denial.query
        .join(PriorAuth)
        .filter(
            Denial.id == denial_id,
            PriorAuth.practice_id == current_user.practice_id
        ).first_or_404())

    denial.appeal_letter  = request.form.get('appeal_letter', denial.appeal_letter)
    denial.appeal_status  = request.form.get('appeal_status', denial.appeal_status)
    denial.outcome_notes  = request.form.get('outcome_notes', '').strip()

    recovery = request.form.get('recovery_amount', '')
    if recovery:
        try:
            denial.recovery_amount = float(recovery)
        except ValueError:
            pass

    db.session.commit()
    flash('Denial record updated.', 'success')
    return redirect(url_for('prior_auth.view_auth', auth_id=denial.prior_auth_id))
